<a href="https://colab.research.google.com/github/VitikaJain25/HealthCareNLPCourse/blob/main/Tensorflow_%26_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Tensorflow is Deep Learning Package.
import tensorflow as tf
# Keras is based on Tensorflow & it supports high end APIs.
import tensorflow.keras as keras

# Tensor is N-Dimentional representation of array of data for various ranks like scalar:tensor(Rank 0), vector:tensor(Rank 1), Matrix(Rank 2), Tensor(3 or More).


In [2]:
# Creating a constant of scalar type
# scalar with tensor rank = 0, shape =0, dtype = int32 bits
# numpy indicates the value.
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
# scalar with tensor rank = 0, shape = 0, dtype = int8 (-128 to 127)
const_1 = tf.constant(127, dtype = 'int8')
print(const_1)

tf.Tensor(127, shape=(), dtype=int8)


In [4]:
const_1.numpy()

127

In [5]:
# Shows the tensor shape
const_1.shape

TensorShape([])

## Vectors

In [6]:
# Vector with Rank = 1
const_2 = tf.constant([20., 40., 60., 80., 15], dtype = 'float16')
print(const_2)

tf.Tensor([20. 40. 60. 80. 15.], shape=(5,), dtype=float16)


In [7]:
# tensor rank = 1
const_2.shape

TensorShape([5])

In [9]:
const_3 = tf.constant([20, 40, 60, 80, 15], dtype = 'int16')
print(const_3)

tf.Tensor([20 40 60 80 15], shape=(5,), dtype=int16)


In [10]:
# Changing / Typecasting the data type.
tf.cast(const_3, dtype = 'int32')

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([20, 40, 60, 80, 15], dtype=int32)>

In [11]:
# Typecasting from one tensor data type to another.
tf.cast(const_3, dtype = 'float32')

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([20., 40., 60., 80., 15.], dtype=float32)>

## Tensor Matrix

In [14]:
# Vector with rank = 2
const_4 = tf.constant([[220, 120, 260],
                      [112, 150, 190],
                      [220, 240, 180]], dtype = 'int16')
print(const_4)

tf.Tensor(
[[220 120 260]
 [112 150 190]
 [220 240 180]], shape=(3, 3), dtype=int16)


In [15]:
const_4.shape

TensorShape([3, 3])

In [17]:
const_4.numpy()

array([[220, 120, 260],
       [112, 150, 190],
       [220, 240, 180]], dtype=int16)

## Tensor N-D Array

In [20]:
const_5 = tf.constant([[[220, 120, 260],
                      [112, 150, 190],
                      [220, 240, 180]],
                      [[220, 120, 260],
                      [112, 150, 190],
                      [220, 240, 180]]], dtype = 'int16')
print (const_5)

tf.Tensor(
[[[220 120 260]
  [112 150 190]
  [220 240 180]]

 [[220 120 260]
  [112 150 190]
  [220 240 180]]], shape=(2, 3, 3), dtype=int16)
